// Code pack generation for `ocean build`.
//
// Compiles `.check.yaml` files into standalone, human-readable scripts using
// Handlebars templates. Generated scripts are checked into packs/ so users
// can browse, audit, and run them without installing OCEAN.
//
// Supported targets:
//   api-script  — Bash + curl + jq (universal)
//   gh-cli      — Bash + GitHub CLI (gh)

use std::io::Write;
use std::path::Path;

use anyhow::{Context, Result};
use handlebars::Handlebars;
use serde_json::json;

use crate::check::definition::CheckDefinition;
use crate::check::loader::load_definitions_from_dir;

// ─── Target ───────────────────────────────────────────────────────────────────

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum BuildTarget {
    ApiScript,
    GhCli,
}

impl BuildTarget {
    pub fn from_str(s: &str) -> Result<Self> {
        match s.to_lowercase().as_str() {
            "api-script" | "api_script" => Ok(Self::ApiScript),
            "gh-cli" | "gh_cli" => Ok(Self::GhCli),
            other => Err(anyhow::anyhow!(
                "unknown build target '{other}'; expected: api-script, gh-cli"
            )),
        }
    }

    pub fn slug(&self) -> &'static str {
        match self {
            Self::ApiScript => "api-script",
            Self::GhCli => "gh-cli",
        }
    }

    pub fn extension(&self) -> &'static str {
        "sh"
    }
}

// ─── Templates ────────────────────────────────────────────────────────────────

const API_SCRIPT_TEMPLATE: &str = r#"#!/usr/bin/env bash
# {{check.id}} — {{check.name}}
# {{check.description}}
#
# Profile: {{check.profile}} | Source: {{check.source}}
# Generated by: ocean build --target api-script
#
# Compliance references:
#   CIS:      {{check.references.cis}}
#   NIST:     {{check.references.nist}}
#   SOC 2:    {{check.references.soc2}}
#   ISO 27001:{{check.references.iso27001}}
#   PCI DSS:  {{check.references.pci_dss}}

set -euo pipefail

# ── Credentials ──────────────────────────────────────────────────────────────
{{#each check.credentials}}
if [[ -z "${{name}}" ]]; then
  echo "ERROR: Required environment variable {{name}} is not set" >&2
  exit 1
fi
{{/each}}

# ── Inputs ───────────────────────────────────────────────────────────────────
{{#each check.inputs}}
{{name}}="$(printenv {{env}} || echo '')"
if [[ -z "${{name}}" ]]; then
  echo "ERROR: Required input '{{name}}' not set via env var {{env}}" >&2
  exit 1
fi
{{/each}}

# ── Check steps ──────────────────────────────────────────────────────────────
{{#each check.steps}}
echo "Step: {{id}}"
RESPONSE_{{@index}}=$(curl -s -o /tmp/ocean_body_{{@index}}.json -w "%{http_code}" \
  -X {{method}} \
{{#each headers}}  -H "{{key}}: {{value}}" \
{{/each}}  "{{url}}")
echo "  HTTP $RESPONSE_{{@index}}"
{{/each}}

# ── Results ──────────────────────────────────────────────────────────────────
echo ""
echo "Results for {{check.id}} — {{check.name}}"
cat /tmp/ocean_body_0.json | jq . 2>/dev/null || cat /tmp/ocean_body_0.json
"#;

const GH_CLI_TEMPLATE: &str = r#"#!/usr/bin/env bash
# {{check.id}} — {{check.name}}
# {{check.description}}
#
# Profile: {{check.profile}} | Source: {{check.source}}
# Generated by: ocean build --target gh-cli
# Requires: gh (GitHub CLI), jq
#
# Compliance references:
#   CIS:      {{check.references.cis}}
#   NIST:     {{check.references.nist}}
#   SOC 2:    {{check.references.soc2}}
#   ISO 27001:{{check.references.iso27001}}

set -euo pipefail

# ── Prerequisites ─────────────────────────────────────────────────────────────
if ! command -v gh &>/dev/null; then
  echo "ERROR: gh (GitHub CLI) is required. Install: https://cli.github.com" >&2
  exit 1
fi

if ! gh auth status &>/dev/null; then
  echo "ERROR: Not authenticated. Run: gh auth login" >&2
  exit 1
fi

# ── Inputs ───────────────────────────────────────────────────────────────────
{{#each check.inputs}}
{{name}}="$(printenv {{env}} || echo '')"
if [[ -z "${{name}}" ]]; then
  echo "ERROR: Required input '{{name}}' not set via env var {{env}}" >&2
  exit 1
fi
{{/each}}

# ── Check steps ──────────────────────────────────────────────────────────────
{{#each check.steps}}
echo "Step: {{id}}"
RESPONSE_{{@index}}=$(gh api "{{gh_path}}" 2>&1) || {
  echo "  WARN: gh api call failed for step {{id}}"
  RESPONSE_{{@index}}=""
}
{{/each}}

# ── Results ──────────────────────────────────────────────────────────────────
echo ""
echo "Results for {{check.id}} — {{check.name}}"
BODY_0="${RESPONSE_0:-}"
echo "$BODY_0" | jq . 2>/dev/null || echo "$BODY_0"

{{#if check.remediation_cli}}
# ── Remediation (if needed) ──────────────────────────────────────────────────
# If this check is failing, run the following to remediate:
# {{check.remediation_cli}}
{{/if}}
"#;

// ─── Build context ────────────────────────────────────────────────────────────

/// Flatten a CheckDefinition into a Handlebars-compatible JSON context.
fn build_context(def: &CheckDefinition) -> serde_json::Value {
    let credentials: Vec<_> = def
        .credentials
        .iter()
        .map(|(name, cred)| {
            json!({
                "name": name,
                "type": cred.cred_type,
                "required": cred.required,
            })
        })
        .collect();

    let inputs: Vec<_> = def
        .inputs
        .iter()
        .map(|(name, inp)| {
            json!({
                "name": name,
                "env": inp.env,
                "description": inp.description,
                "required": inp.required,
            })
        })
        .collect();

    let steps: Vec<_> = def
        .steps
        .iter()
        .enumerate()
        .map(|(i, step)| {
            let method = &step.request.method;
            let url = &step.request.url;
            // Strip https://api.github.com prefix for gh-cli path
            let gh_path = url
                .strip_prefix("https://api.github.com/")
                .unwrap_or(url)
                .to_string();
            let headers: Vec<_> = step
                .request
                .headers
                .iter()
                .map(|(k, v)| json!({ "key": k, "value": v }))
                .collect();
            json!({
                "id": step.id,
                "method": method,
                "url": url,
                "gh_path": gh_path,
                "headers": headers,
                "index": i,
            })
        })
        .collect();

    let remediation_cli = def
        .remediation
        .as_ref()
        .and_then(|r| r.cli.as_ref())
        .map(|c| c.command.clone());

    json!({
        "check": {
            "id": def.id,
            "name": def.name,
            "description": def.description.trim(),
            "source": def.source,
            "profile": def.profile,
            "tags": def.tags,
            "credentials": credentials,
            "inputs": inputs,
            "steps": steps,
            "remediation_cli": remediation_cli,
            "references": {
                "cis": format_string_or_vec(&def.references.cis),
                "nist": format_string_or_vec(&def.references.nist),
                "soc2": format_string_or_vec(&def.references.soc2),
                "iso27001": format_string_or_vec(&def.references.iso27001),
                "pci_dss": format_string_or_vec(&def.references.pci_dss),
                "disa_stig": format_string_or_vec(&def.references.disa_stig),
            },
        }
    })
}

fn format_string_or_vec(val: &crate::check::definition::StringOrVec) -> String {
    match val {
        crate::check::definition::StringOrVec::One(s) => s.clone(),
        crate::check::definition::StringOrVec::Many(v) => v.join(", "),
        crate::check::definition::StringOrVec::None => String::new(),
    }
}

// ─── Generation ───────────────────────────────────────────────────────────────

/// Generate code packs for all checks in `checks_dir` for the given target.
///
/// Returns the number of files written (or that would be written in `--diff` mode).
pub fn generate<W: Write>(
    out: &mut W,
    checks_dir: &Path,
    target: &BuildTarget,
    output_dir: &Path,
    validate_only: bool,
    diff_only: bool,
    filter: Option<&str>,
) -> Result<usize> {
    let defs = load_definitions_from_dir(checks_dir);

    let filtered: Vec<&CheckDefinition> = defs
        .iter()
        .filter(|d| filter.is_none_or(|f| d.id.starts_with(f) || d.source == f))
        .collect();

    if filtered.is_empty() {
        writeln!(out, "No checks found in {}", checks_dir.display())?;
        return Ok(0);
    }

    let mut hb = Handlebars::new();
    hb.set_strict_mode(false);

    let template_src = match target {
        BuildTarget::ApiScript => API_SCRIPT_TEMPLATE,
        BuildTarget::GhCli => GH_CLI_TEMPLATE,
    };

    hb.register_template_string("pack", template_src)
        .context("register Handlebars template")?;

    if validate_only {
        writeln!(out, "Validated {} check(s) — templates OK", filtered.len())?;
        return Ok(filtered.len());
    }

    if !diff_only {
        std::fs::create_dir_all(output_dir)
            .with_context(|| format!("create output dir {}", output_dir.display()))?;
    }

    let mut written = 0;
    for def in &filtered {
        if def.implementation == "native" {
            let filename = format!("{}.stub.{}", def.id.to_lowercase(), target.extension());
            let stub = format!(
                "#!/usr/bin/env bash\n# {} — {}\n# This check requires OCEAN CLI (native implementation).\necho \"Run: ocean observe {}\"\n",
                def.id, def.name, def.id
            );
            write_or_diff(out, output_dir, &filename, &stub, diff_only)?;
            written += 1;
            continue;
        }

        let ctx = build_context(def);
        let rendered = hb
            .render("pack", &ctx)
            .with_context(|| format!("render template for {}", def.id))?;

        let filename = format!(
            "{}.{}",
            def.id.to_lowercase().replace('.', "-"),
            target.extension()
        );
        write_or_diff(out, output_dir, &filename, &rendered, diff_only)?;
        written += 1;
    }

    if diff_only {
        writeln!(out, "Would write {written} file(s) to {}", output_dir.display())?;
    } else {
        writeln!(
            out,
            "Generated {written} {} pack(s) → {}",
            target.slug(),
            output_dir.display()
        )?;
    }

    Ok(written)
}

fn write_or_diff<W: Write>(
    out: &mut W,
    dir: &Path,
    filename: &str,
    content: &str,
    diff_only: bool,
) -> Result<()> {
    if diff_only {
        writeln!(out, "  + {filename}")?;
        return Ok(());
    }
    let path = dir.join(filename);
    std::fs::write(&path, content)
        .with_context(|| format!("write {}", path.display()))?;
    // Make scripts executable
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let mut perms = std::fs::metadata(&path)?.permissions();
        perms.set_mode(0o755);
        std::fs::set_permissions(&path, perms)?;
    }
    writeln!(out, "  ✓ {filename}")?;
    Ok(())
}

// ─── Tests ────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;
    use tempfile::TempDir;

    fn write_check(dir: &Path, filename: &str, content: &str) {
        std::fs::write(dir.join(filename), content).unwrap();
    }

    const SIMPLE_CHECK: &str = r#"
id: GH-TEST-01
name: Test Check
description: "A test check"
source: github
profile: L1
credentials:
  GITHUB_TOKEN:
    type: api_token
    required: true
inputs:
  org:
    description: GitHub org
    env: GITHUB_ORG
    required: true
steps:
  - id: get_org
    action: api_call
    request:
      method: GET
      url: "https://api.github.com/orgs/{{org}}"
      headers:
        Authorization: "Bearer {{GITHUB_TOKEN}}"
assertions: []
references:
  soc2: CC6.1
  nist: "IA-2"
"#;

    #[test]
    fn build_target_from_str() {
        assert_eq!(BuildTarget::from_str("api-script").unwrap(), BuildTarget::ApiScript);
        assert_eq!(BuildTarget::from_str("gh-cli").unwrap(), BuildTarget::GhCli);
        assert_eq!(BuildTarget::from_str("api_script").unwrap(), BuildTarget::ApiScript);
        assert!(BuildTarget::from_str("unknown").is_err());
    }

    #[test]
    fn build_target_slug() {
        assert_eq!(BuildTarget::ApiScript.slug(), "api-script");
        assert_eq!(BuildTarget::GhCli.slug(), "gh-cli");
    }

    #[test]
    fn generate_api_script() {
        let checks_dir = TempDir::new().unwrap();
        let output_dir = TempDir::new().unwrap();
        write_check(checks_dir.path(), "gh-test-01.check.yaml", SIMPLE_CHECK);

        let mut out = Vec::new();
        let count = generate(
            &mut out,
            checks_dir.path(),
            &BuildTarget::ApiScript,
            output_dir.path(),
            false,
            false,
            None,
        )
        .unwrap();

        assert_eq!(count, 1);
        let script_path = output_dir.path().join("gh-test-01.sh");
        assert!(script_path.exists());
        let content = std::fs::read_to_string(&script_path).unwrap();
        assert!(content.contains("GH-TEST-01"));
        assert!(content.contains("Test Check"));
        assert!(content.contains("curl"));
        assert!(content.starts_with("#!/usr/bin/env bash"));
    }

    #[test]
    fn generate_gh_cli() {
        let checks_dir = TempDir::new().unwrap();
        let output_dir = TempDir::new().unwrap();
        write_check(checks_dir.path(), "gh-test-01.check.yaml", SIMPLE_CHECK);

        let mut out = Vec::new();
        let count = generate(
            &mut out,
            checks_dir.path(),
            &BuildTarget::GhCli,
            output_dir.path(),
            false,
            false,
            None,
        )
        .unwrap();

        assert_eq!(count, 1);
        let script_path = output_dir.path().join("gh-test-01.sh");
        assert!(script_path.exists());
        let content = std::fs::read_to_string(&script_path).unwrap();
        assert!(content.contains("GH-TEST-01"));
        assert!(content.contains("gh api"));
    }

    #[test]
    fn generate_validate_only() {
        let checks_dir = TempDir::new().unwrap();
        let output_dir = TempDir::new().unwrap();
        write_check(checks_dir.path(), "gh-test-01.check.yaml", SIMPLE_CHECK);

        let mut out = Vec::new();
        let count = generate(
            &mut out,
            checks_dir.path(),
            &BuildTarget::ApiScript,
            output_dir.path(),
            true,
            false,
            None,
        )
        .unwrap();

        assert_eq!(count, 1);
        // No files written in validate mode
        assert!(!output_dir.path().join("gh-test-01.sh").exists());
        let s = String::from_utf8(out).unwrap();
        assert!(s.contains("Validated"));
    }

    #[test]
    fn generate_diff_only() {
        let checks_dir = TempDir::new().unwrap();
        let output_dir = PathBuf::from("/tmp/nonexistent-ocean-test-output");
        write_check(checks_dir.path(), "gh-test-01.check.yaml", SIMPLE_CHECK);

        let mut out = Vec::new();
        let count = generate(
            &mut out,
            checks_dir.path(),
            &BuildTarget::ApiScript,
            &output_dir,
            false,
            true,
            None,
        )
        .unwrap();

        assert_eq!(count, 1);
        // No files actually written
        assert!(!output_dir.join("gh-test-01.sh").exists());
        let s = String::from_utf8(out).unwrap();
        assert!(s.contains("Would write"));
    }

    #[test]
    fn generate_filter_by_source() {
        let checks_dir = TempDir::new().unwrap();
        let output_dir = TempDir::new().unwrap();
        write_check(checks_dir.path(), "gh-test-01.check.yaml", SIMPLE_CHECK);

        let mut out = Vec::new();
        // Filter for "okta" source — should produce 0 results
        let count = generate(
            &mut out,
            checks_dir.path(),
            &BuildTarget::ApiScript,
            output_dir.path(),
            false,
            false,
            Some("okta"),
        )
        .unwrap();
        assert_eq!(count, 0);
    }

    #[test]
    fn generate_empty_checks_dir() {
        let checks_dir = TempDir::new().unwrap();
        let output_dir = TempDir::new().unwrap();

        let mut out = Vec::new();
        let count = generate(
            &mut out,
            checks_dir.path(),
            &BuildTarget::ApiScript,
            output_dir.path(),
            false,
            false,
            None,
        )
        .unwrap();
        assert_eq!(count, 0);
    }

    #[test]
    fn build_context_references() {
        let checks_dir = TempDir::new().unwrap();
        write_check(checks_dir.path(), "gh-test-01.check.yaml", SIMPLE_CHECK);
        let defs = load_definitions_from_dir(checks_dir.path());
        assert_eq!(defs.len(), 1);
        let ctx = build_context(&defs[0]);
        assert_eq!(ctx["check"]["references"]["soc2"], "CC6.1");
        assert_eq!(ctx["check"]["references"]["nist"], "IA-2");
    }
}
