// Code pack generation for `ocean build`.
//
// Compiles `.check.yaml` files into standalone, human-readable scripts using
// Handlebars templates. Generated scripts are checked into packs/ so users
// can browse, audit, and run them without installing OCEAN.
//
// Supported targets:
//   api-script  — Bash + curl + jq (universal)
//   gh-cli      — Bash + GitHub CLI (gh)

use std::io::Write;
use std::path::Path;

use anyhow::{Context, Result};
use handlebars::Handlebars;
use serde_json::json;

use crate::check::definition::CheckDefinition;
use crate::check::loader::load_definitions_from_dir;

// ─── Target ───────────────────────────────────────────────────────────────────

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum BuildTarget {
    ApiScript,
    GhCli,
    PythonSdk,
    GoSdk,
    OpaRego,
    Terraform,
    SigmaRule,
}

impl BuildTarget {
    pub fn from_str(s: &str) -> Result<Self> {
        match s.to_lowercase().as_str() {
            "api-script" | "api_script" => Ok(Self::ApiScript),
            "gh-cli" | "gh_cli" => Ok(Self::GhCli),
            "python-sdk" | "python_sdk" | "python" => Ok(Self::PythonSdk),
            "go-sdk" | "go_sdk" | "go" => Ok(Self::GoSdk),
            "opa-rego" | "opa_rego" | "rego" => Ok(Self::OpaRego),
            "terraform" | "tf" => Ok(Self::Terraform),
            "sigma-rule" | "sigma_rule" | "sigma" => Ok(Self::SigmaRule),
            other => Err(anyhow::anyhow!(
                "unknown build target '{other}'; expected: api-script, gh-cli, python-sdk, go-sdk, opa-rego, terraform, sigma-rule"
            )),
        }
    }

    pub fn slug(&self) -> &'static str {
        match self {
            Self::ApiScript => "api-script",
            Self::GhCli => "gh-cli",
            Self::PythonSdk => "python-sdk",
            Self::GoSdk => "go-sdk",
            Self::OpaRego => "opa-rego",
            Self::Terraform => "terraform",
            Self::SigmaRule => "sigma-rule",
        }
    }

    pub fn extension(&self) -> &'static str {
        match self {
            Self::ApiScript | Self::GhCli => "sh",
            Self::PythonSdk => "py",
            Self::GoSdk => "go",
            Self::OpaRego => "rego",
            Self::Terraform => "tf",
            Self::SigmaRule => "yml",
        }
    }
}

// ─── Templates ────────────────────────────────────────────────────────────────

const API_SCRIPT_TEMPLATE: &str = r#"#!/usr/bin/env bash
# {{check.id}} — {{check.name}}
# {{check.description}}
#
# Profile: {{check.profile}} | Source: {{check.source}}
# Generated by: ocean build --target api-script
#
# Compliance references:
#   CIS:      {{check.references.cis}}
#   NIST:     {{check.references.nist}}
#   SOC 2:    {{check.references.soc2}}
#   ISO 27001:{{check.references.iso27001}}
#   PCI DSS:  {{check.references.pci_dss}}

set -euo pipefail

# ── Credentials ──────────────────────────────────────────────────────────────
{{#each check.credentials}}
if [[ -z "${{name}}" ]]; then
  echo "ERROR: Required environment variable {{name}} is not set" >&2
  exit 1
fi
{{/each}}

# ── Inputs ───────────────────────────────────────────────────────────────────
{{#each check.inputs}}
{{name}}="$(printenv {{env}} || echo '')"
if [[ -z "${{name}}" ]]; then
  echo "ERROR: Required input '{{name}}' not set via env var {{env}}" >&2
  exit 1
fi
{{/each}}

# ── Check steps ──────────────────────────────────────────────────────────────
{{#each check.steps}}
echo "Step: {{id}}"
RESPONSE_{{@index}}=$(curl -s -o /tmp/ocean_body_{{@index}}.json -w "%{http_code}" \
  -X {{method}} \
{{#each headers}}  -H "{{key}}: {{value}}" \
{{/each}}  "{{url}}")
echo "  HTTP $RESPONSE_{{@index}}"
{{/each}}

# ── Results ──────────────────────────────────────────────────────────────────
echo ""
echo "Results for {{check.id}} — {{check.name}}"
cat /tmp/ocean_body_0.json | jq . 2>/dev/null || cat /tmp/ocean_body_0.json
"#;

const GH_CLI_TEMPLATE: &str = r#"#!/usr/bin/env bash
# {{check.id}} — {{check.name}}
# {{check.description}}
#
# Profile: {{check.profile}} | Source: {{check.source}}
# Generated by: ocean build --target gh-cli
# Requires: gh (GitHub CLI), jq
#
# Compliance references:
#   CIS:      {{check.references.cis}}
#   NIST:     {{check.references.nist}}
#   SOC 2:    {{check.references.soc2}}
#   ISO 27001:{{check.references.iso27001}}

set -euo pipefail

# ── Prerequisites ─────────────────────────────────────────────────────────────
if ! command -v gh &>/dev/null; then
  echo "ERROR: gh (GitHub CLI) is required. Install: https://cli.github.com" >&2
  exit 1
fi

if ! gh auth status &>/dev/null; then
  echo "ERROR: Not authenticated. Run: gh auth login" >&2
  exit 1
fi

# ── Inputs ───────────────────────────────────────────────────────────────────
{{#each check.inputs}}
{{name}}="$(printenv {{env}} || echo '')"
if [[ -z "${{name}}" ]]; then
  echo "ERROR: Required input '{{name}}' not set via env var {{env}}" >&2
  exit 1
fi
{{/each}}

# ── Check steps ──────────────────────────────────────────────────────────────
{{#each check.steps}}
echo "Step: {{id}}"
RESPONSE_{{@index}}=$(gh api "{{gh_path}}" 2>&1) || {
  echo "  WARN: gh api call failed for step {{id}}"
  RESPONSE_{{@index}}=""
}
{{/each}}

# ── Results ──────────────────────────────────────────────────────────────────
echo ""
echo "Results for {{check.id}} — {{check.name}}"
BODY_0="${RESPONSE_0:-}"
echo "$BODY_0" | jq . 2>/dev/null || echo "$BODY_0"

{{#if check.remediation_cli}}
# ── Remediation (if needed) ──────────────────────────────────────────────────
# If this check is failing, run the following to remediate:
# {{check.remediation_cli}}
{{/if}}
"#;

const PYTHON_SDK_TEMPLATE: &str = r#"#!/usr/bin/env python3
"""{{check.id}} — {{check.name}}

{{check.description}}

Profile: {{check.profile}} | Source: {{check.source}}
Generated by: ocean build --target python-sdk

Compliance references:
  CIS:       {{check.references.cis}}
  NIST:      {{check.references.nist}}
  SOC 2:     {{check.references.soc2}}
  ISO 27001: {{check.references.iso27001}}
  PCI DSS:   {{check.references.pci_dss}}
"""

import json
import os
import sys
import urllib.request

# ── Credentials ──────────────────────────────────────────────────────────────
{{#each check.credentials}}
{{name}} = os.environ.get("{{name}}")
if not {{name}}:
    print("ERROR: Required environment variable {{name}} is not set", file=sys.stderr)
    sys.exit(1)
{{/each}}

# ── Inputs ───────────────────────────────────────────────────────────────────
{{#each check.inputs}}
{{name}} = os.environ.get("{{env}}", "")
if not {{name}}:
    print("ERROR: Required input '{{name}}' not set via env var {{env}}", file=sys.stderr)
    sys.exit(1)
{{/each}}


def api_call(method: str, url: str, headers: dict) -> dict:
    """Make an HTTP API call and return parsed JSON."""
    req = urllib.request.Request(url, method=method, headers=headers)
    try:
        with urllib.request.urlopen(req) as resp:
            return json.loads(resp.read().decode())
    except urllib.error.HTTPError as e:
        print(f"  HTTP {e.code}: {e.reason}", file=sys.stderr)
        return {}


# ── Check steps ──────────────────────────────────────────────────────────────
results = {}
{{#each check.steps}}
print("Step: {{id}}")
results["step_{{@index}}"] = api_call(
    "{{method}}",
    f"{{url}}",
    { {{#each headers}}"{{key}}": f"{{value}}", {{/each}} },
)
{{/each}}

# ── Results ──────────────────────────────────────────────────────────────────
print()
print(f"Results for {{check.id}} — {{check.name}}")
for key, val in results.items():
    print(json.dumps(val, indent=2))
"#;

const GO_SDK_TEMPLATE: &str = r#"// {{check.id}} — {{check.name}}
// {{check.description}}
//
// Profile: {{check.profile}} | Source: {{check.source}}
// Generated by: ocean build --target go-sdk
//
// Compliance references:
//   CIS:       {{check.references.cis}}
//   NIST:      {{check.references.nist}}
//   SOC 2:     {{check.references.soc2}}
//   ISO 27001: {{check.references.iso27001}}

package main

import (
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
)

func main() {
	// ── Credentials ──────────────────────────────────────────────────────
	{{#each check.credentials}}
	{{name}} := os.Getenv("{{name}}")
	if {{name}} == "" {
		fmt.Fprintf(os.Stderr, "ERROR: Required environment variable {{name}} is not set\n")
		os.Exit(1)
	}
	{{/each}}

	// ── Inputs ───────────────────────────────────────────────────────────
	{{#each check.inputs}}
	{{name}} := os.Getenv("{{env}}")
	if {{name}} == "" {
		fmt.Fprintf(os.Stderr, "ERROR: Required input '{{name}}' not set via env var {{env}}\n")
		os.Exit(1)
	}
	{{/each}}

	client := &http.Client{}

	// ── Check steps ──────────────────────────────────────────────────────
	{{#each check.steps}}
	fmt.Println("Step: {{id}}")
	req{{@index}}, _ := http.NewRequest("{{method}}", fmt.Sprintf("{{url}}"), nil)
	{{#each headers}}
	req{{@../index}}.Header.Set("{{key}}", fmt.Sprintf("{{value}}"))
	{{/each}}
	resp{{@index}}, err := client.Do(req{{@index}})
	if err != nil {
		fmt.Fprintf(os.Stderr, "  ERROR: %v\n", err)
	} else {
		body{{@index}}, _ := io.ReadAll(resp{{@index}}.Body)
		resp{{@index}}.Body.Close()
		fmt.Printf("  HTTP %d\n", resp{{@index}}.StatusCode)
		var pretty{{@index}} interface{}
		if json.Unmarshal(body{{@index}}, &pretty{{@index}}) == nil {
			out{{@index}}, _ := json.MarshalIndent(pretty{{@index}}, "", "  ")
			fmt.Println(string(out{{@index}}))
		}
	}
	{{/each}}

	_ = {{#each check.credentials}}{{name}}; _ = {{/each}}""
	_ = {{#each check.inputs}}{{name}}; _ = {{/each}}""
}
"#;

const OPA_REGO_TEMPLATE: &str = r#"# {{check.id}} — {{check.name}}
# {{check.description}}
#
# Profile: {{check.profile}} | Source: {{check.source}}
# Generated by: ocean build --target opa-rego
#
# Compliance references:
#   CIS:       {{check.references.cis}}
#   NIST:      {{check.references.nist}}
#   SOC 2:     {{check.references.soc2}}
#   ISO 27001: {{check.references.iso27001}}
#   PCI DSS:   {{check.references.pci_dss}}

package ocean.{{check.source}}.{{check.id}}

import rego.v1

# Metadata annotations for OPA
# METADATA
# title: {{check.name}}
# description: {{check.description}}
# custom:
#   check_id: {{check.id}}
#   source: {{check.source}}
#   profile: {{check.profile}}

default allow := false

# Input is expected to be the API response for this check.
# Feed the result of the corresponding API call as input.

allow if {
    input.status == "compliant"
}

violations contains msg if {
    not allow
    msg := "{{check.id}}: {{check.name}} — check failed"
}
"#;

const TERRAFORM_TEMPLATE: &str = r#"# {{check.id}} — {{check.name}}
# {{check.description}}
#
# Profile: {{check.profile}} | Source: {{check.source}}
# Generated by: ocean build --target terraform
#
# Compliance references:
#   CIS:       {{check.references.cis}}
#   NIST:      {{check.references.nist}}
#   SOC 2:     {{check.references.soc2}}
#   ISO 27001: {{check.references.iso27001}}

# This file defines the expected state for check {{check.id}}.
# Use with terraform plan to detect drift from the desired configuration.

variable "{{check.source}}_token" {
  type        = string
  sensitive   = true
  description = "API token for {{check.source}}"
}

{{#each check.inputs}}
variable "{{name}}" {
  type        = string
  description = "{{description}}"
}
{{/each}}

# Check definition as a data source for reference by other modules.
locals {
  check_id      = "{{check.id}}"
  check_name    = "{{check.name}}"
  check_source  = "{{check.source}}"
  check_profile = "{{check.profile}}"
}

# Terraform provider configuration and resource definitions should be
# customized for your infrastructure. The check metadata above provides
# the compliance context for your Terraform state.
"#;

const SIGMA_RULE_TEMPLATE: &str = r#"title: "{{check.name}}"
id: {{check.id}}
status: experimental
description: "{{check.description}}"
references:
  - https://grc.engineering
author: grc-engineering (ocean build)
date: 2026/01/01
tags:
{{#each check.tags}}  - {{this}}
{{/each}}  - ocean.{{check.source}}

logsource:
  product: {{check.source}}
  service: audit

detection:
  selection:
    eventType: "configuration.change"
  condition: selection

fields:
  - eventType
  - actor
  - target
  - timestamp

falsepositives:
  - Legitimate configuration changes by authorized administrators

level: medium

# Compliance references:
#   CIS:       {{check.references.cis}}
#   NIST:      {{check.references.nist}}
#   SOC 2:     {{check.references.soc2}}
#   ISO 27001: {{check.references.iso27001}}
#   PCI DSS:   {{check.references.pci_dss}}
"#;

// ─── Build context ────────────────────────────────────────────────────────────

/// Flatten a CheckDefinition into a Handlebars-compatible JSON context.
fn build_context(def: &CheckDefinition) -> serde_json::Value {
    let credentials: Vec<_> = def
        .credentials
        .iter()
        .map(|(name, cred)| {
            json!({
                "name": name,
                "type": cred.cred_type,
                "required": cred.required,
            })
        })
        .collect();

    let inputs: Vec<_> = def
        .inputs
        .iter()
        .map(|(name, inp)| {
            json!({
                "name": name,
                "env": inp.env,
                "description": inp.description,
                "required": inp.required,
            })
        })
        .collect();

    let steps: Vec<_> = def
        .steps
        .iter()
        .enumerate()
        .map(|(i, step)| {
            let method = &step.request.method;
            let url = &step.request.url;
            // Strip https://api.github.com prefix for gh-cli path
            let gh_path = url
                .strip_prefix("https://api.github.com/")
                .unwrap_or(url)
                .to_string();
            let headers: Vec<_> = step
                .request
                .headers
                .iter()
                .map(|(k, v)| json!({ "key": k, "value": v }))
                .collect();
            json!({
                "id": step.id,
                "method": method,
                "url": url,
                "gh_path": gh_path,
                "headers": headers,
                "index": i,
            })
        })
        .collect();

    let remediation_cli = def
        .remediation
        .as_ref()
        .and_then(|r| r.cli.as_ref())
        .map(|c| c.command.clone());

    json!({
        "check": {
            "id": def.id,
            "name": def.name,
            "description": def.description.trim(),
            "source": def.source,
            "profile": def.profile,
            "tags": def.tags,
            "credentials": credentials,
            "inputs": inputs,
            "steps": steps,
            "remediation_cli": remediation_cli,
            "references": {
                "cis": format_string_or_vec(&def.references.cis),
                "nist": format_string_or_vec(&def.references.nist),
                "soc2": format_string_or_vec(&def.references.soc2),
                "iso27001": format_string_or_vec(&def.references.iso27001),
                "pci_dss": format_string_or_vec(&def.references.pci_dss),
                "disa_stig": format_string_or_vec(&def.references.disa_stig),
            },
        }
    })
}

fn format_string_or_vec(val: &crate::check::definition::StringOrVec) -> String {
    match val {
        crate::check::definition::StringOrVec::One(s) => s.clone(),
        crate::check::definition::StringOrVec::Many(v) => v.join(", "),
        crate::check::definition::StringOrVec::None => String::new(),
    }
}

// ─── Generation ───────────────────────────────────────────────────────────────

/// Generate code packs for all checks in `checks_dir` for the given target.
///
/// Returns the number of files written (or that would be written in `--diff` mode).
pub fn generate<W: Write>(
    out: &mut W,
    checks_dir: &Path,
    target: &BuildTarget,
    output_dir: &Path,
    validate_only: bool,
    diff_only: bool,
    filter: Option<&str>,
) -> Result<usize> {
    let defs = load_definitions_from_dir(checks_dir);

    let filtered: Vec<&CheckDefinition> = defs
        .iter()
        .filter(|d| filter.is_none_or(|f| d.id.starts_with(f) || d.source == f))
        .collect();

    if filtered.is_empty() {
        writeln!(out, "No checks found in {}", checks_dir.display())?;
        return Ok(0);
    }

    let mut hb = Handlebars::new();
    hb.set_strict_mode(false);

    let template_src = match target {
        BuildTarget::ApiScript => API_SCRIPT_TEMPLATE,
        BuildTarget::GhCli => GH_CLI_TEMPLATE,
        BuildTarget::PythonSdk => PYTHON_SDK_TEMPLATE,
        BuildTarget::GoSdk => GO_SDK_TEMPLATE,
        BuildTarget::OpaRego => OPA_REGO_TEMPLATE,
        BuildTarget::Terraform => TERRAFORM_TEMPLATE,
        BuildTarget::SigmaRule => SIGMA_RULE_TEMPLATE,
    };

    hb.register_template_string("pack", template_src)
        .context("register Handlebars template")?;

    if validate_only {
        writeln!(out, "Validated {} check(s) — templates OK", filtered.len())?;
        return Ok(filtered.len());
    }

    if !diff_only {
        std::fs::create_dir_all(output_dir)
            .with_context(|| format!("create output dir {}", output_dir.display()))?;
    }

    let mut written = 0;
    for def in &filtered {
        if def.implementation == "native" {
            let filename = format!("{}.stub.{}", def.id.to_lowercase(), target.extension());
            let stub = format!(
                "#!/usr/bin/env bash\n# {} — {}\n# This check requires OCEAN CLI (native implementation).\necho \"Run: ocean observe {}\"\n",
                def.id, def.name, def.id
            );
            write_or_diff(out, output_dir, &filename, &stub, diff_only)?;
            written += 1;
            continue;
        }

        let ctx = build_context(def);
        let rendered = hb
            .render("pack", &ctx)
            .with_context(|| format!("render template for {}", def.id))?;

        let filename = format!(
            "{}.{}",
            def.id.to_lowercase().replace('.', "-"),
            target.extension()
        );
        write_or_diff(out, output_dir, &filename, &rendered, diff_only)?;
        written += 1;
    }

    if diff_only {
        writeln!(out, "Would write {written} file(s) to {}", output_dir.display())?;
    } else {
        writeln!(
            out,
            "Generated {written} {} pack(s) → {}",
            target.slug(),
            output_dir.display()
        )?;
    }

    Ok(written)
}

fn write_or_diff<W: Write>(
    out: &mut W,
    dir: &Path,
    filename: &str,
    content: &str,
    diff_only: bool,
) -> Result<()> {
    if diff_only {
        writeln!(out, "  + {filename}")?;
        return Ok(());
    }
    let path = dir.join(filename);
    std::fs::write(&path, content)
        .with_context(|| format!("write {}", path.display()))?;
    // Make scripts executable
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let mut perms = std::fs::metadata(&path)?.permissions();
        perms.set_mode(0o755);
        std::fs::set_permissions(&path, perms)?;
    }
    writeln!(out, "  ✓ {filename}")?;
    Ok(())
}

// ─── Tests ────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;
    use tempfile::TempDir;

    fn write_check(dir: &Path, filename: &str, content: &str) {
        std::fs::write(dir.join(filename), content).unwrap();
    }

    const SIMPLE_CHECK: &str = r#"
id: GH-TEST-01
name: Test Check
description: "A test check"
source: github
profile: L1
credentials:
  GITHUB_TOKEN:
    type: api_token
    required: true
inputs:
  org:
    description: GitHub org
    env: GITHUB_ORG
    required: true
steps:
  - id: get_org
    action: api_call
    request:
      method: GET
      url: "https://api.github.com/orgs/{{org}}"
      headers:
        Authorization: "Bearer {{GITHUB_TOKEN}}"
assertions: []
references:
  soc2: CC6.1
  nist: "IA-2"
"#;

    #[test]
    fn build_target_from_str() {
        assert_eq!(BuildTarget::from_str("api-script").unwrap(), BuildTarget::ApiScript);
        assert_eq!(BuildTarget::from_str("gh-cli").unwrap(), BuildTarget::GhCli);
        assert_eq!(BuildTarget::from_str("api_script").unwrap(), BuildTarget::ApiScript);
        assert_eq!(BuildTarget::from_str("python-sdk").unwrap(), BuildTarget::PythonSdk);
        assert_eq!(BuildTarget::from_str("python").unwrap(), BuildTarget::PythonSdk);
        assert_eq!(BuildTarget::from_str("go-sdk").unwrap(), BuildTarget::GoSdk);
        assert_eq!(BuildTarget::from_str("go").unwrap(), BuildTarget::GoSdk);
        assert_eq!(BuildTarget::from_str("opa-rego").unwrap(), BuildTarget::OpaRego);
        assert_eq!(BuildTarget::from_str("rego").unwrap(), BuildTarget::OpaRego);
        assert_eq!(BuildTarget::from_str("terraform").unwrap(), BuildTarget::Terraform);
        assert_eq!(BuildTarget::from_str("tf").unwrap(), BuildTarget::Terraform);
        assert_eq!(BuildTarget::from_str("sigma-rule").unwrap(), BuildTarget::SigmaRule);
        assert_eq!(BuildTarget::from_str("sigma").unwrap(), BuildTarget::SigmaRule);
        assert!(BuildTarget::from_str("unknown").is_err());
    }

    #[test]
    fn build_target_slug() {
        assert_eq!(BuildTarget::ApiScript.slug(), "api-script");
        assert_eq!(BuildTarget::GhCli.slug(), "gh-cli");
        assert_eq!(BuildTarget::PythonSdk.slug(), "python-sdk");
        assert_eq!(BuildTarget::GoSdk.slug(), "go-sdk");
        assert_eq!(BuildTarget::OpaRego.slug(), "opa-rego");
        assert_eq!(BuildTarget::Terraform.slug(), "terraform");
        assert_eq!(BuildTarget::SigmaRule.slug(), "sigma-rule");
    }

    #[test]
    fn build_target_extensions() {
        assert_eq!(BuildTarget::PythonSdk.extension(), "py");
        assert_eq!(BuildTarget::GoSdk.extension(), "go");
        assert_eq!(BuildTarget::OpaRego.extension(), "rego");
        assert_eq!(BuildTarget::Terraform.extension(), "tf");
        assert_eq!(BuildTarget::SigmaRule.extension(), "yml");
    }

    #[test]
    fn generate_api_script() {
        let checks_dir = TempDir::new().unwrap();
        let output_dir = TempDir::new().unwrap();
        write_check(checks_dir.path(), "gh-test-01.check.yaml", SIMPLE_CHECK);

        let mut out = Vec::new();
        let count = generate(
            &mut out,
            checks_dir.path(),
            &BuildTarget::ApiScript,
            output_dir.path(),
            false,
            false,
            None,
        )
        .unwrap();

        assert_eq!(count, 1);
        let script_path = output_dir.path().join("gh-test-01.sh");
        assert!(script_path.exists());
        let content = std::fs::read_to_string(&script_path).unwrap();
        assert!(content.contains("GH-TEST-01"));
        assert!(content.contains("Test Check"));
        assert!(content.contains("curl"));
        assert!(content.starts_with("#!/usr/bin/env bash"));
    }

    #[test]
    fn generate_gh_cli() {
        let checks_dir = TempDir::new().unwrap();
        let output_dir = TempDir::new().unwrap();
        write_check(checks_dir.path(), "gh-test-01.check.yaml", SIMPLE_CHECK);

        let mut out = Vec::new();
        let count = generate(
            &mut out,
            checks_dir.path(),
            &BuildTarget::GhCli,
            output_dir.path(),
            false,
            false,
            None,
        )
        .unwrap();

        assert_eq!(count, 1);
        let script_path = output_dir.path().join("gh-test-01.sh");
        assert!(script_path.exists());
        let content = std::fs::read_to_string(&script_path).unwrap();
        assert!(content.contains("GH-TEST-01"));
        assert!(content.contains("gh api"));
    }

    #[test]
    fn generate_validate_only() {
        let checks_dir = TempDir::new().unwrap();
        let output_dir = TempDir::new().unwrap();
        write_check(checks_dir.path(), "gh-test-01.check.yaml", SIMPLE_CHECK);

        let mut out = Vec::new();
        let count = generate(
            &mut out,
            checks_dir.path(),
            &BuildTarget::ApiScript,
            output_dir.path(),
            true,
            false,
            None,
        )
        .unwrap();

        assert_eq!(count, 1);
        // No files written in validate mode
        assert!(!output_dir.path().join("gh-test-01.sh").exists());
        let s = String::from_utf8(out).unwrap();
        assert!(s.contains("Validated"));
    }

    #[test]
    fn generate_diff_only() {
        let checks_dir = TempDir::new().unwrap();
        let output_dir = PathBuf::from("/tmp/nonexistent-ocean-test-output");
        write_check(checks_dir.path(), "gh-test-01.check.yaml", SIMPLE_CHECK);

        let mut out = Vec::new();
        let count = generate(
            &mut out,
            checks_dir.path(),
            &BuildTarget::ApiScript,
            &output_dir,
            false,
            true,
            None,
        )
        .unwrap();

        assert_eq!(count, 1);
        // No files actually written
        assert!(!output_dir.join("gh-test-01.sh").exists());
        let s = String::from_utf8(out).unwrap();
        assert!(s.contains("Would write"));
    }

    #[test]
    fn generate_filter_by_source() {
        let checks_dir = TempDir::new().unwrap();
        let output_dir = TempDir::new().unwrap();
        write_check(checks_dir.path(), "gh-test-01.check.yaml", SIMPLE_CHECK);

        let mut out = Vec::new();
        // Filter for "okta" source — should produce 0 results
        let count = generate(
            &mut out,
            checks_dir.path(),
            &BuildTarget::ApiScript,
            output_dir.path(),
            false,
            false,
            Some("okta"),
        )
        .unwrap();
        assert_eq!(count, 0);
    }

    #[test]
    fn generate_empty_checks_dir() {
        let checks_dir = TempDir::new().unwrap();
        let output_dir = TempDir::new().unwrap();

        let mut out = Vec::new();
        let count = generate(
            &mut out,
            checks_dir.path(),
            &BuildTarget::ApiScript,
            output_dir.path(),
            false,
            false,
            None,
        )
        .unwrap();
        assert_eq!(count, 0);
    }

    #[test]
    fn generate_python_sdk() {
        let checks_dir = TempDir::new().unwrap();
        let output_dir = TempDir::new().unwrap();
        write_check(checks_dir.path(), "gh-test-01.check.yaml", SIMPLE_CHECK);

        let mut out = Vec::new();
        let count = generate(&mut out, checks_dir.path(), &BuildTarget::PythonSdk, output_dir.path(), false, false, None).unwrap();
        assert_eq!(count, 1);
        let path = output_dir.path().join("gh-test-01.py");
        assert!(path.exists());
        let content = std::fs::read_to_string(&path).unwrap();
        assert!(content.contains("GH-TEST-01"));
        assert!(content.contains("urllib.request"));
    }

    #[test]
    fn generate_go_sdk() {
        let checks_dir = TempDir::new().unwrap();
        let output_dir = TempDir::new().unwrap();
        write_check(checks_dir.path(), "gh-test-01.check.yaml", SIMPLE_CHECK);

        let mut out = Vec::new();
        let count = generate(&mut out, checks_dir.path(), &BuildTarget::GoSdk, output_dir.path(), false, false, None).unwrap();
        assert_eq!(count, 1);
        let path = output_dir.path().join("gh-test-01.go");
        assert!(path.exists());
        let content = std::fs::read_to_string(&path).unwrap();
        assert!(content.contains("GH-TEST-01"));
        assert!(content.contains("net/http"));
    }

    #[test]
    fn generate_opa_rego() {
        let checks_dir = TempDir::new().unwrap();
        let output_dir = TempDir::new().unwrap();
        write_check(checks_dir.path(), "gh-test-01.check.yaml", SIMPLE_CHECK);

        let mut out = Vec::new();
        let count = generate(&mut out, checks_dir.path(), &BuildTarget::OpaRego, output_dir.path(), false, false, None).unwrap();
        assert_eq!(count, 1);
        let path = output_dir.path().join("gh-test-01.rego");
        assert!(path.exists());
        let content = std::fs::read_to_string(&path).unwrap();
        assert!(content.contains("package ocean.github"));
        assert!(content.contains("default allow"));
    }

    #[test]
    fn generate_terraform() {
        let checks_dir = TempDir::new().unwrap();
        let output_dir = TempDir::new().unwrap();
        write_check(checks_dir.path(), "gh-test-01.check.yaml", SIMPLE_CHECK);

        let mut out = Vec::new();
        let count = generate(&mut out, checks_dir.path(), &BuildTarget::Terraform, output_dir.path(), false, false, None).unwrap();
        assert_eq!(count, 1);
        let path = output_dir.path().join("gh-test-01.tf");
        assert!(path.exists());
        let content = std::fs::read_to_string(&path).unwrap();
        assert!(content.contains("variable"));
        assert!(content.contains("github_token"));
    }

    #[test]
    fn generate_sigma_rule() {
        let checks_dir = TempDir::new().unwrap();
        let output_dir = TempDir::new().unwrap();
        write_check(checks_dir.path(), "gh-test-01.check.yaml", SIMPLE_CHECK);

        let mut out = Vec::new();
        let count = generate(&mut out, checks_dir.path(), &BuildTarget::SigmaRule, output_dir.path(), false, false, None).unwrap();
        assert_eq!(count, 1);
        let path = output_dir.path().join("gh-test-01.yml");
        assert!(path.exists());
        let content = std::fs::read_to_string(&path).unwrap();
        assert!(content.contains("logsource"));
        assert!(content.contains("detection"));
    }

    #[test]
    fn build_context_references() {
        let checks_dir = TempDir::new().unwrap();
        write_check(checks_dir.path(), "gh-test-01.check.yaml", SIMPLE_CHECK);
        let defs = load_definitions_from_dir(checks_dir.path());
        assert_eq!(defs.len(), 1);
        let ctx = build_context(&defs[0]);
        assert_eq!(ctx["check"]["references"]["soc2"], "CC6.1");
        assert_eq!(ctx["check"]["references"]["nist"], "IA-2");
    }
}
